# Comments here
title: Julian Reif4s

minimal_mistakes_skin: contrast 
#search: false
#repository: reifjulian/reifjulian.github.io

# Build settings
#markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "splash"
